### ISSUE TITLE
.form-row.field-box broken on chrome

### ISSUE THREAD

**Issue by douglasmiranda** [douglasmiranda/django-admin-bootstrap#65]
change unset to none in forms.css:
```css
.form-row.field-box {
    clear: none;
}
```
